# Spring configurations
spring:
  main:
    allow-bean-definition-overriding: false
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/king-store-db?useSSL=false
    username: postgres
    password: postgres

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
    database: postgresql
    open-in-view: true

#Token configuration
jwt:
  secret: =========================KING=STORE=============================
  expiration: 1800000
  refreshExpiration: 2700000
